"""
Verification engine for ASVE.

This module coordinates verification rules against scientific
dependency graphs and aggregates reproducibility findings.
"""

from __future__ import annotations

from asve.graph.graph import ScientificGraph
from asve.verification.base import VerificationRule
from asve.verification.finding import Finding


class VerificationEngine:
    """
    Execute registered verification rules.
    """

    def __init__(self) -> None:
        self._rules: list[VerificationRule] = []

    def register(
        self,
        rule: VerificationRule,
    ) -> None:
        """
        Register a verification rule.

        Parameters
        ----------
        rule
            Verification rule instance.
        """
        self._rules.append(rule)

    def verify(
        self,
        graph: ScientificGraph,
    ) -> tuple[Finding, ...]:
        """
        Run all applicable verification rules.

        Parameters
        ----------
        graph
            Scientific dependency graph.

        Returns
        -------
        tuple[Finding, ...]
            Findings generated by verification.
        """
        findings: list[Finding] = []

        for rule in self._rules:
            if rule.supports(graph):
                findings.extend(
                    rule.verify(graph)
                )

        return tuple(findings)

    def clear(self) -> None:
        """
        Remove all registered rules.
        """
        self._rules.clear()

    def __len__(self) -> int:
        """
        Return number of registered rules.
        """
        return len(self._rules)

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}"
            f"(rules={len(self)})"
        )


engine = VerificationEngine()


__all__ = [
    "VerificationEngine",
    "engine",
]
